apiVersion: apps/v1
kind: Deployment
metadata:
  name: managemovie
  labels:
    app: managemovie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managemovie
  template:
    metadata:
      labels:
        app: managemovie
    spec:
      containers:
        - name: managemovie
          image: "username/managemovie:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
